### ISSUE TITLE
expand / reduce selction with strg - click

### ISSUE THREAD

**Issue by marcdakar** [stephan281094/vue-drag-select#10]
hi there, this is a very useful component,
is it possible to integrate a select/deselect function, so you can expand/reduce the selection with strg - mouseclick on items
if not planned can you give me a hint, how to start to implement it
thank you very much
marc

**Comment by stephan281094** [comment]
Hi @marcdakar, thank you for showing interest in this project!
The requested feature is definitely something I'd like to have, but it is not (yet) planned.

If you're interested in implementing this feature yourself, the following might be helpful.
At the moment we have a reactive 'selectedItems' property where we save what items are currently selected. In order to add the functionality you describe, we can add a new reactive property that keeps track of items that you strg - click.
We can then pass `selectedItems` to the slot, filtering out the items from the new reactive property.

Let me know if that makes sense. Have a great day!

**Comment by marcdakar** [comment]
hi stephan, for now i catch in the mousedown event of the component the STRG press and if pressed prevent the mouse-drag ... so i can do the select/deselect logic in parent with @click.strg
this works very nice, if you like i can give an example
best regards marc

**Comment by stephan281094** [comment]
An example would be great! I'm sure it'd be helpful for people wanting to do the same.

**Comment by marcdakar** [comment]
hi stephan, for sure
https://teste223.lima-city.de/
make a selection -> click CTRL and select/deselect with mouse
and i make a fork
many greetings marc

**Comment by Ham3D** [comment]
I'm also interested in this feature.

**Comment by marcdakar** [comment]
hi hamed, i have made a fork of this component, with the desired feature ...

**Comment by stephan281094** [comment]
@marcdakar Feel free to submit a PR to make this part of `vue-drag-select`.

**Comment by marcdakar** [comment]
hi stephan, i have ..  but keep in mind that i did this never before ...

**Comment by stephan281094** [comment]
That's awesome! I'll make sure to review it later this week.

**Comment by stephan281094** [comment]
This is now part of 0.2.0. You can use shift to expand your selection!
